baseURL = 'https://hgoos.github.io/hatich-goose/'
locale = 'en-us'
title = 'The Archives'
theme = 'ananke'


[params.anake]
cover_dimming_class = "bg-dark-green-40"
body_classses = "avenir bg-dark-green"
github = "https://github.com/hgoos"
linkedin = "https://linkedin.com/in/helena-goos-29a3232b4"

[taxonomies]
  tag = "tags"
  category = "categories"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true   # treat soft line breaks as <br>
      unsafe = true 



[params.anake.social]
  [params.ananke.social.follow]
    networks = ["github", "linkedin"]
  
  [params.ananke.social.github]
    profilelink = "https://github.com/hgoos"

  [params.ananke.social.linkedin]
    profilelink = "https://linkedin.com/in/helena-goos-29a3232b4"


[[menu.main]]
  name = "Writing"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Poetry"
  url = "/writing/poetry"
  parent = "Writing"
  weight = 2
  params.newtab = true

[[menu.main]]
  name = "Prose"
  url = "/writing/prose"
  parent = "Writing"
  weight = 3

[[menu.main]]
  name = "Comics"
  url = "/"
  weight = 4

[[menu.main]]
  name = "Captain's Blog"
  url = "/captainsblog/"
  weight = 5



[[menu.main]]
  name = "Art"
  url = "/comics/comics-art"
  parent = "Comics"
  weight = 6

[[menu.main]]
  name = "Scripts"
  url = "/comics/comics-scrpt"
  parent = "Comics"
  weight = 7

[[menu.main]]
  name = "Other Work"
  url = "/"
  weight = 8

[[menu.main]]
  name = "International Examiner"
  url = "https://iexaminer.org/author/helena-goos/"
  parent = "Other Work"
  weight = 9

[[menu.main]]
  name = "Marketing Choices"
  url = "https://marketingchoices.com/2024/11/07/helena-goos/"
  parent = "Other Work"
  weight = 10

[[menu.main]]
  name = "Seattle Arts and Lectures"
  url = "/tags/seattle-arts-and-lectures"
  parent = "Other Work"
  weight = 11


[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 12

[caches]
  [caches.images]
    dir = ':cacheDir/images'




